#!/usr/bin/env bash
# files/init-redis-cluster.sh
#
# 一键把 3 台机器上的 6 个 Redis 实例（每机 1 主 1 从）组成一个 Redis Cluster。
#
# 用法：
#   NODE1=10.0.0.11 NODE2=10.0.0.12 NODE3=10.0.0.13 \
#   PORT_BASE=7000 PASS=secretpass \
#   ./scripts/init-redis-cluster.sh
#
# 前置条件：
#   1. 6 个 Redis 实例已经在每台机器上启动（见 docs/plans/IM三机集群部署方案_20260728.md §9.2.3）。
#      每个实例需要开启 cluster-enabled yes + bind 内网 IP。
#   2. 集群总线端口 = PORT_BASE + 10000 也必须可达（即 17000/17001/…），
#      否则 gossip + cluster meet 会失败。
#   3. redis-cli 与目标实例之间的网络可达。
#
# 该脚本会：
#   - 调用 redis-cli --cluster create 把 6 个节点组成 cluster（--cluster-replicas 1）
#   - 自动应答 yes（每个 master 分配一个 slave）
#   - 校验 cluster info + cluster nodes
#   - 写入 /etc/redis-cluster.env 备份当前集群节点列表，便于后续 add-node/rebalance
#
# 安全提示：脚本只在初始化阶段使用一次，不要在已有数据的集群上重复执行。

set -euo pipefail

NODE1="${NODE1:?NODE1 must be set, e.g. 10.0.0.11}"
NODE2="${NODE2:?NODE2 must be set, e.g. 10.0.0.12}"
NODE3="${NODE3:?NODE3 must be set, e.g. 10.0.0.13}"
PORT_BASE="${PORT_BASE:-7000}"
PASS="${PASS:-}"
REDIS_CLI="${REDIS_CLI:-redis-cli}"

AUTH_FLAG=()
if [[ -n "$PASS" ]]; then
  AUTH_FLAG=(-a "$PASS" --no-auth-warning)
fi

# Compose the 6-node address list (node1:7000, node1:7001, node2:7000, node2:7001, …).
NODES=(
  "${NODE1}:${PORT_BASE}"
  "${NODE1}:$((PORT_BASE + 1))"
  "${NODE2}:${PORT_BASE}"
  "${NODE2}:$((PORT_BASE + 1))"
  "${NODE3}:${PORT_BASE}"
  "${NODE3}:$((PORT_BASE + 1))"
)

echo "[cluster] About to create Redis Cluster with the following nodes:"
printf '  - %s\n' "${NODES[@]}"

# --cluster-replicas 1 means each master gets exactly one replica, which is
# what the IM deployment requires (3 masters + 3 replicas = 6 nodes total).
# The `echo yes` is fed to redis-cli to auto-accept the slot allocation
# proposed by the cluster manager.
echo yes | "$REDIS_CLI" "${AUTH_FLAG[@]}" \
  --cluster create "${NODES[@]}" \
  --cluster-replicas 1

echo "[cluster] create done, verifying with cluster info / cluster nodes ..."

FIRST_NODE="${NODES[0]}"
FIRST_HOST="${FIRST_NODE%:*}"
FIRST_PORT="${FIRST_NODE##*:}"
cluster_state="$("$REDIS_CLI" "${AUTH_FLAG[@]}" -h "$FIRST_HOST" -p "$FIRST_PORT" cluster info | grep '^cluster_state' | awk -F: '{print $2}' | tr -d ' \r\n')"

if [[ "$cluster_state" != "ok" ]]; then
  echo "[cluster] FAIL: cluster_state=$cluster_state (expected ok)" >&2
  exit 1
fi

echo "[cluster] cluster_state=ok"

# Print the slot layout for the operator's logs.
"$REDIS_CLI" "${AUTH_FLAG[@]}" -h "$FIRST_HOST" -p "$FIRST_PORT" cluster nodes

# Persist the node list so later operations (rebalance, add-node, remove-node)
# can re-use it without recomputing.
BACKUP_FILE="${BACKUP_FILE:-/etc/redis-cluster.env}"
{
  echo "# Generated by init-redis-cluster.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "export NODE1='$NODE1'"
  echo "export NODE2='$NODE2'"
  echo "export NODE3='$NODE3'"
  echo "export PORT_BASE='$PORT_BASE'"
  printf 'export NODES=("%s")\n' "${NODES[@]}"
} > "$BACKUP_FILE"
chmod 600 "$BACKUP_FILE" || true

echo "[cluster] node list saved to $BACKUP_FILE"
echo "[cluster] DONE."